### ISSUE TITLE
"Native code compile failed!!"

### ISSUE THREAD

**Issue by arleym** [carpages/gemini-boilerplate#2]
I think something is fundamentally wrong, npm fails. It's the oldest Gemini repo, so maybe it's not surprising some stuff is out of date.

**Comment by mattdrose** [comment]
Probably. Haven't been using this, and I have no tests setup :s. Is it `npm i` that's failing?

**Comment by arleym** [comment]
Ha! I closed this hoping you wouldn't notice. My rookie-ness at VVV was the issue. I got it kickin' now!
